### ISSUE TITLE
请问如何使用音频处理器 (APU)这个内置的功能呢

### ISSUE THREAD

**Issue by lzpfmh** [kendryte/kendryte-standalone-demo#15]
请问如何使用音频处理器 (APU)这个内置的功能呢，在官方Standalone SDK 编程指南中没有提出这个使用方法，只有i2s的使用方法，这个APU的处理功能是已经包含在i2s中了么？官方文档中说的《可以支持多达 16 个方向的声源同时扫描预处理与波束形成》，这个又如何使用呢？求解，谢谢

**Comment by zzxcanaan** [comment]
抱歉，目前还没有支持APU。
