### ISSUE TITLE
win10  IDE  INCBIN 

### ISSUE THREAD

**Issue by hydys** [kendryte/kendryte-standalone-demo#39]
使用IDE在win10（64位）环境下编译face_detect例程：
#define LOAD_KMODEL_FROM_FLASH 0
#if LOAD_KMODEL_FROM_FLASH
#define KMODEL_SIZE (380 * 1024)
uint8_t *model_data;
#else
INCBIN(model, "detect.kmodel");
#endif
此处报错：
应输入标识符[50,15]

**Comment by GongT** [comment]
INC_BIN的实现非常不符合通常的C语言规范，它依赖编译结果的路径，然而IDE无法保证编译结果到底在哪，所以没办法支持。

本来应该把模型烧到flash里的（这样程序也小）。
包管理器里面有改过的例程。

**Comment by hydys** [comment]
好的，非常感谢！
