### ISSUE TITLE
Which demo is for green board~

### ISSUE THREAD

**Issue by ysh329** [kendryte/kendryte-standalone-demo#4]
Hi, I'm from forum [Compile standalone-demo Error | Kendryte 勘智](https://forum.kendryte.com/topic/39/compile-standalone-demo-error/4). 

Thanks in advance. `_(:з)∠)_`

**Comment by ly0** [comment]
@ysh329 looks familiar...

**Comment by vowstar** [comment]
Please ask our sales to change green board to black board.
