### ISSUE TITLE
I2S TDM模式相关问题/ I2S TDM Mode Problem

### ISSUE THREAD

**Issue by 1998CN** [kendryte/kendryte-standalone-demo#47]
我在I2S TDM模式下，通过4个通道连接了8个超声麦克风，在设置DMA接收数据时发现只能设置一个DMA通道，因为需要调用其他的算法，需要获取麦克风的原始数据，我想知道设置DMA通道后，8个麦克风的数据在DMA数组中是怎么排布的，感谢回复。

-----

In the I2S TDM mode, through the four channels connected to the eight ultrasonic microphone, in setting up the DMA receiving data, it found that only set up one DMA channel, because i need to call the other algorithm, need to get the microphone original data, I want to know after setting the DMA channel, 8 of microphone array in the DMA data is how arrangement, thank you.

**Comment by manageryzy** [comment]
找原厂签NDA后有文档
