### ISSUE TITLE
ai_demo_sim download problem

### ISSUE THREAD

**Issue by akioolin** [kendryte/kendryte-standalone-demo#7]
Hi, my enviroment is ubuntu 18.04 LTS.

in ai_demo_sim project,  using cmake to generate ai_demo_sim.bin. 
the next step is using kflash.py to download ai_demo_sim.bin
the following command which I used

sudo python3 ./kflash.py -p /dev/ttyUSB0 -b 2000000 -v ai_demo_sim.bin

the final message is 
[INFO] Rebooting...

which step is wrong?

**Comment by vowstar** [comment]
Do you try to reset the board? If it works, that's normal and no problem. It will open your serial port at final step

**Comment by akioolin** [comment]
Many Thanks.

Finally, I use the windows flash tool to update the board. and wondering what is the default value of kflash.py to put code into board, flash or on-chip?

**Comment by vowstar** [comment]
> Many Thanks.
> 
> Finally, I use the windows flash tool to update the board. and wondering what is the default value of kflash.py to put code into board, flash or on-chip?

I use this parameter program code to flash.
```bash
python3 ../../../../kflash.py/kflash.py -b 2000000 example.bin
```
The default value is program firmware to flash.

**Comment by akioolin** [comment]
OK!

I'll try this way. hope this can work.
